version: "3"

services:

  server:

    build: ./server
    command: python ./webapp/app.py --host=0.0.0.0 # Eller så kan vi ta den .sh filen
    ports:
      - 50008:50008/udp # Station port
      - 5009:5009 # Client port
      - 5000:5000 # Flask app port

  weather_station:

    build: ./station
    command: python ./weather_station_data_sender.py d
    depends_on:
      - server
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build: ./client  # Where to find the docker file
    container_name: user_client
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: python ./weather_app_client.py d
    depends_on:
      - server
