FROM python:latest

WORKDIR /server

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

RUN chmod a+x docker_entrypoint.sh

ENTRYPOINT [ "./docker_entrypoint.sh" ]

# CMD ["python","-u","server.py"]